version: "3.9"

services:
  # when putting this in the top level docker-compose.yml
  # we need to tweak some values
  tailwind:
    build:
      context: ./ # top level: ./tailwind
      dockerfile: Dockerfile
    tty: true
    restart: always
    volumes:
      - ./:/src # top level: ./tailwind:/src
      - ../assets:/dst # top level: ./assets:/dst
      - ../templates:/templates # top level: ./templates:/templates