version: "3.9"

services:
  tailwind:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    restart: always
    volumes:
      - ./:/src
      - ../assets:/dst
      - ../templates:/templates