version: "3.9"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: lenslocked
      POSTGRES_PASSWORD: lenslocked
      POSTGRES_DB: lenslocked
    ports:
       - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - 8080:8080

volumes:
  pgdata: